# Generated by Django 2.2 on 2019-05-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autorzy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idautora', models.IntegerField()),
                ('imie', models.CharField(max_length=250)),
                ('nazwisko', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('numerkontaktowy', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autorzy',
            },
        ),
        migrations.CreateModel(
            name='ksiazki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idksiazki', models.IntegerField()),
                ('nazwa', models.CharField(max_length=250)),
                ('ilosc', models.CharField(max_length=250)),
                ('nrkontakowy', models.IntegerField()),
                ('wydawca', models.CharField(max_length=250)),
                ('pub_date', models.DateTimeField(verbose_name='data wydania')),
            ],
            options={
                'verbose_name': 'Ksiazka',
                'verbose_name_plural': 'Ksiazki',
            },
        ),
        migrations.CreateModel(
            name='Reklamacje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idreklamacji', models.IntegerField()),
                ('reklamacja_date', models.DateTimeField(verbose_name='data reklamacji')),
                ('status_reklamacji', models.IntegerField()),
                ('decyzja', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Reklamacja',
                'verbose_name_plural': 'Reklamacje',
            },
        ),
        migrations.CreateModel(
            name='Uzytkownicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iduzytkownika', models.IntegerField()),
                ('typ', models.IntegerField()),
                ('imie', models.CharField(max_length=250)),
                ('nazwisko', models.CharField(max_length=250)),
                ('miasto', models.CharField(max_length=250)),
                ('numertelefonu', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('from_date', models.DateTimeField(verbose_name='godzina dodania')),
            ],
            options={
                'verbose_name': 'Użytkownik',
                'verbose_name_plural': 'Użytkownicy',
            },
        ),
        migrations.CreateModel(
            name='Zamowienia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idzamowienia', models.IntegerField()),
                ('idrodzaj', models.IntegerField()),
                ('datasprzedazy', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=250)),
                ('datadoreczenia', models.CharField(max_length=250)),
                ('order_date', models.DateTimeField(verbose_name='date zamowienia')),
            ],
            options={
                'verbose_name': 'Zamowienie',
                'verbose_name_plural': 'Zamowienia',
            },
        ),
    ]
