# Generated by Django 2.2 on 2019-06-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fantasty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idFantasty', models.IntegerField()),
                ('nazwa', models.CharField(max_length=250)),
                ('wydawca', models.CharField(max_length=250)),
                ('ilosc', models.CharField(max_length=250)),
                ('pub_date', models.DateTimeField(verbose_name='data wydania')),
            ],
            options={
                'verbose_name': 'Fantast',
                'verbose_name_plural': 'Fantasty',
            },
        ),
        migrations.CreateModel(
            name='Historyczne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idHistorycznych', models.IntegerField()),
                ('nazwa', models.CharField(max_length=250)),
                ('wydawca', models.CharField(max_length=250)),
                ('ilosc', models.CharField(max_length=250)),
                ('pub_date', models.DateTimeField(verbose_name='data wydania')),
            ],
            options={
                'verbose_name': 'Historyczne',
                'verbose_name_plural': 'Historyczne',
            },
        ),
        migrations.CreateModel(
            name='Naukowe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idNaukowych', models.IntegerField()),
                ('nazwa', models.CharField(max_length=250)),
                ('wydawca', models.CharField(max_length=250)),
                ('ilosc', models.CharField(max_length=250)),
                ('pub_date', models.DateTimeField(verbose_name='data wydania')),
            ],
            options={
                'verbose_name': 'Naukowe',
                'verbose_name_plural': 'Naukowe',
            },
        ),
        migrations.CreateModel(
            name='Przygodowe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPrzygodowych', models.IntegerField()),
                ('nazwa', models.CharField(max_length=250)),
                ('wydawca', models.CharField(max_length=250)),
                ('ilosc', models.CharField(max_length=250)),
                ('pub_date', models.DateTimeField(verbose_name='data wydania')),
            ],
            options={
                'verbose_name': 'Przygodowe',
                'verbose_name_plural': 'Przygodowe',
            },
        ),
        migrations.CreateModel(
            name='Sportowe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idSportowych', models.IntegerField()),
                ('nazwa', models.CharField(max_length=250)),
                ('wydawca', models.CharField(max_length=250)),
                ('ilosc', models.CharField(max_length=250)),
                ('pub_date', models.DateTimeField(verbose_name='data wydania')),
            ],
            options={
                'verbose_name': 'Sportowe',
                'verbose_name_plural': 'Sportowe',
            },
        ),
    ]
