# Generated by Django 2.2 on 2019-06-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_fantasty_historyczne_naukowe_przygodowe_sportowe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fantasty',
            name='idFantasty',
        ),
        migrations.RemoveField(
            model_name='historyczne',
            name='idHistorycznych',
        ),
        migrations.RemoveField(
            model_name='naukowe',
            name='idNaukowych',
        ),
        migrations.RemoveField(
            model_name='przygodowe',
            name='idPrzygodowych',
        ),
        migrations.RemoveField(
            model_name='sportowe',
            name='idSportowych',
        ),
        migrations.AlterField(
            model_name='fantasty',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historyczne',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='naukowe',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='przygodowe',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sportowe',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
