# Generated by Django 2.2.2 on 2019-06-15 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20190610_1447'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ksiazki',
            new_name='Inne',
        ),
        migrations.AlterModelOptions(
            name='inne',
            options={'verbose_name': 'Inna', 'verbose_name_plural': 'Inne'},
        ),
    ]
