# Generated by Django 2.2 on 2019-06-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20190615_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autorzy',
            name='idautora',
        ),
        migrations.RemoveField(
            model_name='inne',
            name='idksiazki',
        ),
        migrations.RemoveField(
            model_name='inne',
            name='nrkontakowy',
        ),
        migrations.RemoveField(
            model_name='reklamacje',
            name='idreklamacji',
        ),
        migrations.RemoveField(
            model_name='uzytkownicy',
            name='iduzytkownika',
        ),
        migrations.RemoveField(
            model_name='zamowienia',
            name='idzamowienia',
        ),
        migrations.AlterField(
            model_name='autorzy',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inne',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reklamacje',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='uzytkownicy',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='zamowienia',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
